name: ai_assistant
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # for showing toast messages
  another_flushbar: ^1.12.30

  # for state management
  flutter_bloc: ^8.1.5

  # for showing lottie animations
  lottie: ^3.1.2

  # for local database
  hive: 4.0.0-dev.2
  isar_flutter_libs: ^4.0.0-dev.13

  # for accessing storage path
  path_provider: ^2.1.3

  # for integrating ai
  flutter_gemini: ^2.0.4

  # for picking image
  image_picker: ^1.1.2
  
  # for chat screen ui
  dash_chat_2: ^0.0.21
  
  # for date-time convertor
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
#   flutter_launcher_icons: "^0.13.1"

# flutter_launcher_icons:
#   android: true
#   ios: true
#   image_path: "assets/images/app_logo.png"
#   min_sdk_android: 21 # android min sdk min:16, default 21

  flutter_lints: ^3.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
